apiVersion: v1
kind: ReplicationController
metadata:
  name: ${PO_APP_NAME}
  labels:
    name: ${PO_APP_NAME}
    app: ${APP_NAME}
spec:
  replicas: 1
  selector:
    name: ${PO_APP_NAME}
  template:
    metadata:
      labels:
        name: ${PO_APP_NAME}
    spec:
      volumes:
      - name: db-secrets-volume
        secret:
          secretName: ${SECRET_DB_NAME}
      containers:
      - name: app
        image: ${PO_APP_IMAGE}
        env:
        - name: GIN_MODE
          value: release
        - name: DB_ENV_MYSQL_ROOT_PASSWORD
          value: whatever
        volumeMounts:
        - name: db-secrets-volume
          mountPath: /etc/db-secrets
          readOnly: true
        ports:
        - containerPort: 8080
